### ISSUE TITLE
Thanks, any plans to integrate vue/vuex?

### ISSUE THREAD

**Issue by kosirm** [lukaszmakuch/rosmaro#1]
Hi, thanks for this amazing project! I'm interested if you have any plans to make a vue/vuex starter?
Thanks in advance for any reply!

**Comment by lukaszmakuch** [comment]
Hi Milan, thank you for your question!

I thought about using Vue's render functions for that, effectively making Vue one more VDOM mechanism Rosmaro can drive.

What do you think about this approach?

**Comment by kosirm** [comment]
That would be excellent!
